version: 2.1
orbs:
  bridgecrew: bridgecrew/bridgecrew@<<pipeline.parameters.dev-orb-version>>
  orb-tools: circleci/orb-tools@9.0
parameters:
  run-integration-tests:
    type: boolean
    default: false
  dev-orb-version:
    type: string
    default: "dev:alpha"
jobs:
  integration-test-1:
    executor: bridgecrew/default
    steps:
      - checkout
      - bridgecrew/install
      - bridgecrew/scan:
          directory: "."
          output: "json"
          api-key-variable: "none"
workflows:
  lint_pack-validate_publish-dev:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          requires:
            - orb-tools/lint
      - orb-tools/publish-dev:
          orb-name: bridgecrew/bridgecrew
          requires:
            - orb-tools/pack
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          requires:
            - orb-tools/publish-dev
  integration-tests_prod-release:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - integration-test-1
      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: bridgecrew/bridgecrew
          add-pr-comment: false
          fail-if-semver-not-indicated: false
          publish-version-tag: false
          requires:
            - integration-test-1
          filters:
            branches:
              only: master
