description: |
  Bridgecrew is a static code analysis tool for infrastructure-as-code.
  It scans cloud infrastructure provisioned using Terraform or cloudformation and detects security and compliance misconfigurations.
  Checkov is written in Python and provides a simple method to write and manage policies.
  It follows the CIS Foundations benchmarks where applicable
docker:
  - image: 'cimg/python'
